### ISSUE TITLE
Add ErrorGroup.resolutionStatus Field

### ISSUE THREAD

**Issue by jamesward** [googleapis/java-errorreporting#259]
Recently a new field was added to `ErrorGroup` named `resolutionStatus`:
https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.groups#ErrorGroup

The latest release (`0.120.3-beta`) of this Java lib doesn't seem to have that field. Can it be added?

**Comment by jamesward** [comment]
I believe this field has been added internally, can we sync it?

**Comment by moadi** [comment]
We are in the process of using this library and just ran into this issue as well....I'm on the latest version of `proto-google-cloud-error-reporting-v1beta1`(0.86.32), but it doesn't seem to have this field.

Any word on when this would be released?

**Comment by simonz130** [comment]
This PR #618 should add resolutionStatus field. There was a mixture of pipeline issues that caused this to be delayed.

**Comment by moadi** [comment]
Thanks for the update!
