### ISSUE TITLE
Update introduced Split Packages when used with Java Modules

### ISSUE THREAD

**Issue by frankbojen-oviva** [googleapis/java-errorreporting#682]
Thanks for stopping by to let us know something could be better!

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: 
3. Java version: 11
4. clouderrorreporting version(s): 0.122.x

#### Steps to reproduce

  1. Create a project using java modules with a module-info.java file.
  2. Require both `google.cloud.errorreporting` and `proto.google.cloud.error.reporting.v1beta1`.
  3. Build the module with maven.

Error shown: `module com.example.x reads package com.google.devtools.clouderrorreporting.v1beta1 from both proto.google.cloud.error.reporting.v1beta1 and google.cloud.errorreporting`.

#### Code example

Have a module with pom.xml that includes this library i.e. 

```
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-errorreporting</artifactId>
            <version>0.122.5-beta</version>
        </dependency>
```

```java
// example module-info.java
module com.example.x {
  requires google.cloud.errorreporting;
  requires proto.google.cloud.error.reporting.v1beta1;

  exports com.example.x.api;
}

```

#### Any additional information below

This was introduced in [this](https://github.com/googleapis/java-errorreporting/pull/618) pull request when the error reporting API surface was renamed, and the package was then split between the PROTO library and the client if I understand correctly.

**Comment by thomasrichner-oviva** [comment]
Any update on this? It effectively breaks compatibility with Quarkus :/

**Comment by meredithslota** [comment]
Development of this library has moved to https://github.com/googleapis/google-cloud-java — if this issue is still relevant, can you please file a new issue there? We've significantly improved our process since this issue was filed, though, and a similar issue was recently closed as "obsolete" (https://github.com/googleapis/google-cloud-java/issues/5760). Thanks!
